#!/bin/bash
set -e
if [ $# != 1 ]; then
  echo "Usage: $(basename $0) <container-image>"
  exit 1
fi
kubectl run toolbox-getrelease --rm -it --restart=Never --image "${1,,}" --image-pull-policy=Always -- sh -c "echo;cat /etc/*release*;echo"
